services:
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=kong
      #- POSTGRES_HOST=localhost
      #- POSTGRES_HOST=172.18.0.2
      - POSTGRES_HOST=kong-database
      - POSTGRES_PASSWORD=kongpass
    networks:
      - kong-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
secrets:
  db-password:
    file: db/password.txt
networks:
    kong-net:
      external: true